export interface Donor {
  id: bigint;
  walletAddress: string;
  name: string | null;
  avatar: string | null;
  color: string | null;
  countryCode: string | null;
  anonymous: boolean;
  avatarApproved: boolean;
}

export interface Donation {
  id: bigint;
  donor: Donor;
  dateTime: Date;
  amount: number;
}

export const testDonors: Donor[] = [
  {
    id: 1n,
    walletAddress: "0xabc123...",
    name: "Miloš Petrović",
    avatar:
      "https://media.istockphoto.com/id/1395838909/photo/portrait-of-young-caucasian-men-in-office-school-environment.jpg?s=612x612&w=0&k=20&c=Io5Yro7pVGiLEG4_VF69_8zPWpTI7wieZL8fWrVTHjs=",
    color: "bg-green-400",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: true,
  },
  {
    id: 2n,
    walletAddress: "0xdef456...",
    name: null,
    avatar: null,
    color: null,
    countryCode: "rs",
    anonymous: true,
    avatarApproved: false,
  },
  {
    id: 3n,
    walletAddress: "0x789ghi...",
    name: "Ana Kovač",
    avatar: null,
    color: "bg-orange-400",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: false,
  },
  {
    id: 4n,
    walletAddress: "0xjkl012...",
    name: "Dragan Ilić",
    avatar:
      "https://media.istockphoto.com/id/1444077739/photo/college-study-and-education-student-man-portrait-with-back-to-school-backpack-and-portfolio.jpg?s=612x612&w=0&k=20&c=PAQmqKzYd3OiKhlfrT1DVMQNkGu-drX4rtJ5p6y7D8c=",
    color: "bg-yellow-400",
    countryCode: "me",
    anonymous: false,
    avatarApproved: false,
  },
  {
    id: 5n,
    walletAddress: "0xlmn345...",
    name: null,
    avatar: null,
    color: null,
    countryCode: "rs",
    anonymous: true,
    avatarApproved: false,
  },
  {
    id: 6n,
    walletAddress: "0xopq678...",
    name: "Sara Nikolić",
    avatar:
      "https://media.istockphoto.com/id/1398385367/photo/happy-millennial-business-woman-in-glasses-posing-with-hands-folded.jpg?s=612x612&w=0&k=20&c=Wd2vTDd6tJ5SeEY-aw0WL0bew8TAkyUGVvNQRj3oJFw=",
    color: "#4caf50",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: true,
  },
  {
    id: 7n,
    walletAddress: "0xrst901...",
    name: "Petar Petrović",
    avatar: null,
    color: "bg-green-400",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: false,
  },
  {
    id: 8n,
    walletAddress: "0xuvw234...",
    name: null,
    avatar: null,
    color: null,
    countryCode: "rs",
    anonymous: true,
    avatarApproved: false,
  },
  {
    id: 9n,
    walletAddress: "0xxyz567...",
    name: "Ivana Šarić",
    avatar:
      "https://media.istockphoto.com/id/1289220781/photo/portrait-of-happy-smiling-woman-at-desk.jpg?s=612x612&w=0&k=20&c=FtC05luuxRpiKRj5F84e2CiPf0h_ZuX6o7o5JwlNaJM=",
    color: "bg-red-400",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: true,
  },
  {
    id: 10n,
    walletAddress: "0x000999...",
    name: "Nenad Božić",
    avatar: null,
    color: "bg-blue-400",
    countryCode: "rs",
    anonymous: false,
    avatarApproved: false,
  },
];

export const testDonations: Donation[] = [
  {
    id: BigInt(1),
    donor: testDonors[0],
    dateTime: new Date(Date.now()),
    amount: 0.018258925806482373,
  },
  {
    id: BigInt(2),
    donor: testDonors[1],
    dateTime: new Date(Date.now() - 1 * 86400000),
    amount: 0.078258422064323713,
  },
  {
    id: BigInt(3),
    donor: testDonors[2],
    dateTime: new Date(Date.now() - 2 * 86400000),
    amount: 0.00017963099531836946,
  },
  {
    id: BigInt(4),
    donor: testDonors[3],
    dateTime: new Date(Date.now() - 3 * 86400000),
    amount: 0.0015899393875969726,
  },
  {
    id: BigInt(5),
    donor: testDonors[4],
    dateTime: new Date(Date.now() - 4 * 86400000),
    amount: 0.010995270311064355,
  },
  {
    id: BigInt(6),
    donor: testDonors[5],
    dateTime: new Date(Date.now() - 5 * 86400000),
    amount: 0.08234404745937492,
  },
  {
    id: BigInt(7),
    donor: testDonors[6],
    dateTime: new Date(Date.now() - 6 * 86400000),
    amount: 0.018144665948160155,
  },
  {
    id: BigInt(8),
    donor: testDonors[7],
    dateTime: new Date(Date.now() - 7 * 86400000),
    amount: 0.015721209804931812,
  },
  {
    id: BigInt(9),
    donor: testDonors[8],
    dateTime: new Date(Date.now() - 8 * 86400000),
    amount: 0.0332760799435432,
  },
  {
    id: BigInt(10),
    donor: testDonors[9],
    dateTime: new Date(Date.now() - 9 * 86400000),
    amount: 0.008053350778028245,
  },
];

export const countries = [
  { code: "AD", name: "Андора" },
  { code: "AE", name: "Уједињени Арапски Емирати" },
  { code: "AF", name: "Авганистан" },
  { code: "AG", name: "Антигва и Барбуда" },
  { code: "AI", name: "Ангвила" },
  { code: "AL", name: "Албанија" },
  { code: "AM", name: "Јерменија" },
  { code: "AO", name: "Ангола" },
  { code: "AQ", name: "Антарктик" },
  { code: "AR", name: "Аргентина" },
  { code: "AS", name: "Америчка Самоа" },
  { code: "AT", name: "Аустрија" },
  { code: "AU", name: "Аустралија" },
  { code: "AW", name: "Аруба" },
  { code: "AX", name: "Оландска Острва" },
  { code: "AZ", name: "Азербејџан" },
  { code: "BA", name: "Босна и Херцеговина" },
  { code: "BB", name: "Барбадос" },
  { code: "BD", name: "Бангладеш" },
  { code: "BE", name: "Белгија" },
  { code: "BF", name: "Буркина Фасо" },
  { code: "BG", name: "Бугарска" },
  { code: "BH", name: "Бахреин" },
  { code: "BI", name: "Бурунди" },
  { code: "BJ", name: "Бенин" },
  { code: "BL", name: "Сен Бартелеми" },
  { code: "BM", name: "Бермуда" },
  { code: "BN", name: "Брунеј" },
  { code: "BO", name: "Боливија" },
  { code: "BQ", name: "Карипска Холандија" },
  { code: "BR", name: "Бразил" },
  { code: "BS", name: "Бахами" },
  { code: "BT", name: "Бутан" },
  { code: "BV", name: "Острво Буве" },
  { code: "BW", name: "Боцвана" },
  { code: "BY", name: "Белорусија" },
  { code: "BZ", name: "Белизе" },
  { code: "CA", name: "Канада" },
  { code: "CC", name: "Кокосова (Килингова) Острва" },
  { code: "CD", name: "Конго - Киншаса" },
  { code: "CF", name: "Централноафричка Република" },
  { code: "CG", name: "Конго - Бразавил" },
  { code: "CH", name: "Швајцарска" },
  { code: "CI", name: "Обала Слоноваче" },
  { code: "CK", name: "Кукова Острва" },
  { code: "CL", name: "Чиле" },
  { code: "CM", name: "Камерун" },
  { code: "CN", name: "Кина" },
  { code: "CO", name: "Колумбија" },
  { code: "CR", name: "Костарика" },
  { code: "CU", name: "Куба" },
  { code: "CV", name: "Зеленортска Острва" },
  { code: "CW", name: "Курасао" },
  { code: "CX", name: "Божићно Острво" },
  { code: "CY", name: "Кипар" },
  { code: "CZ", name: "Чешка" },
  { code: "DE", name: "Немачка" },
  { code: "DJ", name: "Џибути" },
  { code: "DK", name: "Данска" },
  { code: "DM", name: "Доминика" },
  { code: "DO", name: "Доминиканска Република" },
  { code: "DZ", name: "Алжир" },
  { code: "EC", name: "Еквадор" },
  { code: "EE", name: "Естонија" },
  { code: "EG", name: "Египат" },
  { code: "EH", name: "Западна Сахара" },
  { code: "ER", name: "Еритреја" },
  { code: "ES", name: "Шпанија" },
  { code: "ET", name: "Етиопија" },
  { code: "FI", name: "Финска" },
  { code: "FJ", name: "Фиџи" },
  { code: "FK", name: "Фокландска Острва" },
  { code: "FM", name: "Микронезија" },
  { code: "FO", name: "Фарска Острва" },
  { code: "FR", name: "Француска" },
  { code: "GA", name: "Габон" },
  { code: "GB", name: "Уједињено Краљевство" },
  { code: "GD", name: "Гренада" },
  { code: "GE", name: "Грузија" },
  { code: "GF", name: "Француска Гвајана" },
  { code: "GG", name: "Гернзи" },
  { code: "GH", name: "Гана" },
  { code: "GI", name: "Гибралтар" },
  { code: "GL", name: "Гренланд" },
  { code: "GM", name: "Гамбија" },
  { code: "GN", name: "Гвинеја" },
  { code: "GP", name: "Гваделуп" },
  { code: "GQ", name: "Екваторијална Гвинеја" },
  { code: "GR", name: "Грчка" },
  { code: "GS", name: "Јужна Џорџија и Јужна Сендвичка Острва" },
  { code: "GT", name: "Гватемала" },
  { code: "GU", name: "Гуам" },
  { code: "GW", name: "Гвинеја-Бисао" },
  { code: "GY", name: "Гвајана" },
  { code: "HK", name: "САР Хонгконг (Кина)" },
  { code: "HM", name: "Острво Херд и Мекдоналдова острва" },
  { code: "HN", name: "Хондурас" },
  { code: "HR", name: "Хрватска" },
  { code: "HT", name: "Хаити" },
  { code: "HU", name: "Мађарска" },
  { code: "ID", name: "Индонезија" },
  { code: "IE", name: "Ирска" },
  { code: "IL", name: "Израел" },
  { code: "IM", name: "Острво Ман" },
  { code: "IN", name: "Индија" },
  { code: "IO", name: "Британска територија Индијског океана" },
  { code: "IQ", name: "Ирак" },
  { code: "IR", name: "Иран" },
  { code: "IS", name: "Исланд" },
  { code: "IT", name: "Италија" },
  { code: "JE", name: "Џерзи" },
  { code: "JM", name: "Јамајка" },
  { code: "JO", name: "Јордан" },
  { code: "JP", name: "Јапан" },
  { code: "KE", name: "Кенија" },
  { code: "KG", name: "Киргистан" },
  { code: "KH", name: "Камбоџа" },
  { code: "KI", name: "Кирибати" },
  { code: "KM", name: "Коморска Острва" },
  { code: "KN", name: "Сент Китс и Невис" },
  { code: "KP", name: "Северна Кореја" },
  { code: "KR", name: "Јужна Кореја" },
  { code: "KW", name: "Кувајт" },
  { code: "KY", name: "Кајманска Острва" },
  { code: "KZ", name: "Казахстан" },
  { code: "LA", name: "Лаос" },
  { code: "LB", name: "Либан" },
  { code: "LC", name: "Света Луција" },
  { code: "LI", name: "Лихтенштајн" },
  { code: "LK", name: "Шри Ланка" },
  { code: "LR", name: "Либерија" },
  { code: "LS", name: "Лесото" },
  { code: "LT", name: "Литванија" },
  { code: "LU", name: "Луксембург" },
  { code: "LV", name: "Летонија" },
  { code: "LY", name: "Либија" },
  { code: "MA", name: "Мароко" },
  { code: "MC", name: "Монако" },
  { code: "MD", name: "Молдавија" },
  { code: "ME", name: "Црна Гора" },
  { code: "MF", name: "Свети Мартин (Француска)" },
  { code: "MG", name: "Мадагаскар" },
  { code: "MH", name: "Маршалска Острва" },
  { code: "MK", name: "Северна Македонија" },
  { code: "ML", name: "Мали" },
  { code: "MM", name: "Мијанмар (Бурма)" },
  { code: "MN", name: "Монголија" },
  { code: "MO", name: "САР Макао (Кина)" },
  { code: "MP", name: "Северна Маријанска Острва" },
  { code: "MQ", name: "Мартиник" },
  { code: "MR", name: "Мауританија" },
  { code: "MS", name: "Монсерат" },
  { code: "MT", name: "Малта" },
  { code: "MU", name: "Маурицијус" },
  { code: "MV", name: "Малдиви" },
  { code: "MW", name: "Малави" },
  { code: "MX", name: "Мексико" },
  { code: "MY", name: "Малезија" },
  { code: "MZ", name: "Мозамбик" },
  { code: "NA", name: "Намибија" },
  { code: "NC", name: "Нова Каледонија" },
  { code: "NE", name: "Нигер" },
  { code: "NF", name: "Острво Норфок" },
  { code: "NG", name: "Нигерија" },
  { code: "NI", name: "Никарагва" },
  { code: "NL", name: "Холандија" },
  { code: "NO", name: "Норвешка" },
  { code: "NP", name: "Непал" },
  { code: "NR", name: "Науру" },
  { code: "NU", name: "Ниуе" },
  { code: "NZ", name: "Нови Зеланд" },
  { code: "OM", name: "Оман" },
  { code: "PA", name: "Панама" },
  { code: "PE", name: "Перу" },
  { code: "PF", name: "Француска Полинезија" },
  { code: "PG", name: "Папуа Нова Гвинеја" },
  { code: "PH", name: "Филипини" },
  { code: "PK", name: "Пакистан" },
  { code: "PL", name: "Пољска" },
  { code: "PM", name: "Сен Пјер и Микелон" },
  { code: "PN", name: "Питкерн" },
  { code: "PR", name: "Порторико" },
  { code: "PS", name: "Палестинске територије" },
  { code: "PT", name: "Португалија" },
  { code: "PW", name: "Палау" },
  { code: "PY", name: "Парагвај" },
  { code: "QA", name: "Катар" },
  { code: "RE", name: "Реинион" },
  { code: "RO", name: "Румунија" },
  { code: "RS", name: "Србија" },
  { code: "RU", name: "Русија" },
  { code: "RW", name: "Руанда" },
  { code: "SA", name: "Саудијска Арабија" },
  { code: "SB", name: "Соломонска Острва" },
  { code: "SC", name: "Сејшели" },
  { code: "SD", name: "Судан" },
  { code: "SE", name: "Шведска" },
  { code: "SG", name: "Сингапур" },
  { code: "SH", name: "Света Јелена" },
  { code: "SI", name: "Словенија" },
  { code: "SJ", name: "Свалбард и Јан Мајен" },
  { code: "SK", name: "Словачка" },
  { code: "SL", name: "Сијера Леоне" },
  { code: "SM", name: "Сан Марино" },
  { code: "SN", name: "Сенегал" },
  { code: "SO", name: "Сомалија" },
  { code: "SR", name: "Суринам" },
  { code: "SS", name: "Јужни Судан" },
  { code: "ST", name: "Сао Томе и Принципе" },
  { code: "SV", name: "Салвадор" },
  { code: "SX", name: "Свети Мартин (Холандија)" },
  { code: "SY", name: "Сирија" },
  { code: "SZ", name: "Свазиленд" },
  { code: "TC", name: "Острва Туркс и Каикос" },
  { code: "TD", name: "Чад" },
  { code: "TF", name: "Француске Јужне Територије" },
  { code: "TG", name: "Того" },
  { code: "TH", name: "Тајланд" },
  { code: "TJ", name: "Таџикистан" },
  { code: "TK", name: "Токелау" },
  { code: "TL", name: "Источни Тимор" },
  { code: "TM", name: "Туркменистан" },
  { code: "TN", name: "Тунис" },
  { code: "TO", name: "Тонга" },
  { code: "TR", name: "Турска" },
  { code: "TT", name: "Тринидад и Тобаго" },
  { code: "TV", name: "Тувалу" },
  { code: "TW", name: "Тајван" },
  { code: "TZ", name: "Танзанија" },
  { code: "UA", name: "Украјина" },
  { code: "UG", name: "Уганда" },
  { code: "UM", name: "Удаљена острва САД" },
  { code: "US", name: "Сједињене Државе" },
  { code: "UY", name: "Уругвај" },
  { code: "UZ", name: "Узбекистан" },
  { code: "VA", name: "Ватикан" },
  { code: "VC", name: "Сент Винсент и Гренадини" },
  { code: "VE", name: "Венецуела" },
  { code: "VG", name: "Британска Девичанска Острва" },
  { code: "VI", name: "Америчка Девичанска Острва" },
  { code: "VN", name: "Вијетнам" },
  { code: "VU", name: "Вануату" },
  { code: "WF", name: "Валис и Футуна" },
  { code: "WS", name: "Самоа" },
  { code: "XK", name: "Косово" },
  { code: "YE", name: "Јемен" },
  { code: "YT", name: "Мајот" },
  { code: "ZA", name: "Јужноафричка Република" },
  { code: "ZM", name: "Замбија" },
  { code: "ZW", name: "Зимбабве" },
];
